### ISSUE TITLE
Limited Flux lora support

### ISSUE THREAD

**Issue by deepfree2023** [siliconflow/BizyAir#149]
### Describe the Bug

Traceback (most recent call last):
  File "K:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "K:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\BizyAir\src\bizyair\nodes_base.py", line 68, in new_func
    return org_func(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\BizyAir\nodes.py", line 239, in decode
    return new_vae.send_request()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\BizyAir\src\bizyair\nodes_io.py", line 88, in send_request
    out = invoker.prompt_server.execute(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\BizyAir\src\bizyair\commands\servers\prompt_server.py", line 54, in execute
    raise RuntimeError(f"Exception: {e=}") from e
RuntimeError: Exception: e=TypeError("'NoneType' object is not subscriptable")
### Steps to Reproduce

Please provide the workflow or steps to reproduce the bug.

### Environment

- **OS:** [Windows 10]
- **Browser:** [chrome]

### Additional Context

Only support flux loras such as XLabs comfy_converted ones, otherwise just report error. Comfyui itself has already support various lora types training by different platforms.

**Comment by deepfree2023** [comment]
Even the meijia lora in the Bizyair example would just report error too.

**Comment by deepfree2023** [comment]
No problem after restart
