### ISSUE TITLE
[BUG] exceed the maximum allowed resolution (Batch Size: 1, Height: 1024, Width: 1024)

### ISSUE THREAD

**Issue by jasoncow007** [siliconflow/BizyAir#163]
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.2\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI-aki-v1.2\custom_nodes\BizyAir\src\bizyair\nodes_base.py", line 68, in new_func
    return org_func(self, **kwargs)
  File "D:\ComfyUI-aki-v1.2\custom_nodes\BizyAir\nodes.py", line 239, in decode
    return new_vae.send_request()
  File "D:\ComfyUI-aki-v1.2\custom_nodes\BizyAir\src\bizyair\nodes_io.py", line 88, in send_request
    out = invoker.prompt_server.execute(
  File "D:\ComfyUI-aki-v1.2\custom_nodes\BizyAir\src\bizyair\commands\servers\prompt_server.py", line 45, in execute
    raise RuntimeError(
RuntimeError: Unexpected error accessing result["data"]["payload"]. Result: {'type': 'success', 'message': None, 'details': None, 'extra_info': None, 'data_status': 'COMPLETED', 'data': {'error': '(False, {\'type\': \'prompt_outputs_failed_validation\', \'message\': \'Prompt outputs failed validation\', \'details\': \'\', \'extra_info\': {}}, [], {\'207\': {\'errors\': [{\'type\': \'value_not_in_list\', \'message\': \'Value not in list\', \'details\': "weight_dtype: \'default\' not in [\'fp8_e4m3fn\']", \'extra_info\': {\'input_name\': \'weight_dtype\', \'input_config\': ([\'fp8_e4m3fn\'], {}), \'received_value\': \'default\'}}], \'dependent_outputs\': [\'138\', \'6\'], \'class_type\': \'BizyAirFluxLoaderOffLine\'}})'}}

### Environment

- **OS:** [Windows 11]
- **Browser:** [edge]

**Comment by doombeaker** [comment]
I am afraid that it's a limit hint, not a bug

**Comment by jasoncow007** [comment]
> I am afraid that it's a limit hint, not a bug

the limit is a bit too hash, could it be 1536x1536 like the other flux size

**Comment by jasoncow007** [comment]
> I am afraid that it's a limit hint, not a bug

this limit comes up with pulid, and now it coz all the workfows made cannot work, if only flux used lora
