### ISSUE TITLE
[BUG] flux alimama CN inpaint failed

### ISSUE THREAD

**Issue by jasoncow007** [siliconflow/BizyAir#228]
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.2\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI-aki-v1.2\custom_nodes\BizyAir\src\bizyair\nodes_base.py", line 70, in new_func
    return org_func(self, **kwargs)
  File "D:\ComfyUI-aki-v1.2\custom_nodes\BizyAir\src\bizyair\nodes_base.py", line 129, in default_function
    return self._process_all_send_request_types(node_ios)
  File "D:\ComfyUI-aki-v1.2\custom_nodes\BizyAir\src\bizyair\nodes_base.py", line 156, in _process_all_send_request_types
    return node_ios[0].send_request()
  File "D:\ComfyUI-aki-v1.2\custom_nodes\BizyAir\src\bizyair\nodes_io.py", line 88, in send_request
    out = invoker.prompt_server.execute(
  File "D:\ComfyUI-aki-v1.2\custom_nodes\BizyAir\src\bizyair\commands\servers\prompt_server.py", line 45, in execute
    raise RuntimeError(
RuntimeError: Unexpected error accessing result["data"]["payload"]. Result: {'type': 'success', 'message': None, 'details': None, 'extra_info': None, 'data_status': 'COMPLETED', 'data': {'error': 'Validation error for ComfyAirLoadData: too many values to unpack (expected 3)'}, 'start_time': 1732079006.237986, 'end_time': 1732079006.3896217, 'task_id': 'e9421b57-73f9-409e-85af-e741dad68317', 'upload_to_s3': None}

**Comment by doombeaker** [comment]
这个问题已经修复，请再试试
