### ISSUE TITLE
[BUG] cannot use for loop with BizyAir Nodes

### ISSUE THREAD

**Issue by AdamShuo** [siliconflow/BizyAir#235]
### Describe the Bug

!!! Exception during processing !!! Node ID must be a string that can be converted to an integer.
Traceback (most recent call last):
  File "F:\ProgramData\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ProgramData\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ProgramData\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ProgramData\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\ProgramData\ComfyUI\custom_nodes\BizyAir\src\bizyair\nodes_base.py", line 70, in new_func
    return org_func(self, **kwargs)
  File "F:\ProgramData\ComfyUI\custom_nodes\BizyAir\nodes.py", line 716, in get_noise
    model = BizyAirNodeIO(
  File "F:\ProgramData\ComfyUI\custom_nodes\BizyAir\src\bizyair\nodes_io.py", line 33, in __init__
    self._validate_node_id(node_id=node_id)
  File "F:\ProgramData\ComfyUI\custom_nodes\BizyAir\src\bizyair\nodes_io.py", line 43, in _validate_node_id
    raise ValueError(
ValueError: Node ID must be a string that can be converted to an integer.

### Environment

- **OS:** [Linux&Windows 10]
- **Browser:** [edge]

![image](https://github.com/user-attachments/assets/9fe0df42-da54-4f4d-9259-422d925eab7f)

It looks like it's caused by the for loop nodes not being able to get the ID of the BizyAir series nodes. Can this be fixed?

**Comment by doombeaker** [comment]
no, the loop is not supported in bizyair now
