### ISSUE TITLE
[BUG] Error raised when run Img2Img workflow for FLUX

### ISSUE THREAD

**Issue by doombeaker** [siliconflow/BizyAir#74]
### Describe the Bug

```
Traceback (most recent call last):
  File "/data/home/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/data/home/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/data/home/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/data/home/ComfyUI/custom_nodes/BizyAir/nodes.py", line 192, in decode
    return new_vae.send_request()
  File "/data/home/ComfyUI/custom_nodes/BizyAir/src/bizyair/image_utils.py", line 243, in send_request
    raise RuntimeError(
RuntimeError: Unexpected error accessing result["data"]["payload"]. Result: {'status': 'error', 'message': 'Input tensor dimensions (1, 16, 64, 64) do not meet the required criteria: B<=4 and C==4 and W*8 <= 1536 and H*8 <= 1536.'}
```

### Steps to Reproduce

[vae_encode_workflow.json](https://github.com/user-attachments/files/16489687/vae_encode_workflow.json)

### Environment

- **OS:** [e.g., Linux Ubuntu 12.04, Windows 10]
- **Browser:** [e.g., chrome, safari]

**Comment by ccssu** [comment]
解决 需要把下面校验 latent 的代码：中 C==4 这个判断去掉。

```python
# comfybridge/projects/comfy_pipeline/node_data_validator.py
if inputs.get("latent", None) is not None:
        B, C, H, W = inputs["latent"]["relay"]["samples"].shape

        if B <= max_batch_size and C == 4 and W * 8 <= max_w and H * 8 <= max_h:
            pass
        else:
            return ValidationResult(
                False,
                f"Input tensor dimensions ({B}, {C}, {H}, {W}) do not meet the required criteria: B<={max_batch_size} and C==4 and W*8 <= {max_w} and H*8 <= {max_h}.",
            )
```

https://docs.comfy.org/essentials/custom_node_datatypes#latent
<img width="785" alt="image" src="https://github.com/user-attachments/assets/be2543f2-16e2-4f8f-9d3d-6567ca92c933">
